# Generated by Django 5.2.6 on 2026-10-01 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_id', models.AutoField(primary_key=True, serialize=False)),
                ('course_code', models.TextField(unique=True)),
                ('title', models.TextField()),
                ('credits', models.SmallIntegerField(default=3)),
            ],
            options={
                'db_table': 'courses',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CourseSection',
            fields=[
                ('section_id', models.AutoField(primary_key=True, serialize=False)),
                ('section_code', models.TextField()),
                ('instructor', models.TextField(blank=True, null=True)),
                ('capacity', models.PositiveIntegerField()),
                ('seats_filled', models.PositiveIntegerField(default=0, editable=False)),
                ('waitlist_capacity', models.PositiveIntegerField(default=10)),
                ('version', models.PositiveIntegerField(default=0, editable=False)),
            ],
            options={
                'db_table': 'course_sections',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Term',
            fields=[
                ('term_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('registration_opens_at', models.DateTimeField(blank=True, null=True)),
                ('registration_closes_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'terms',
                'managed': False,
            },
        ),
    ]
